const CREATE_FILES_TABLE_QUERY = `CREATE TABLE IF NOT EXISTS files (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        filename TEXT NOT NULL,
        filepath TEXT NOT NULL,
        upload_time DATETIME DEFAULT CURRENT_TIMESTAMP
    )`;


const CREATE_TRANSLATIONS_TABLE_QUERY = `CREATE TABLE IF NOT EXISTS translations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sentence TEXT NOT NULL,
    translation TEXT NOT NULL,
    file_id INTEGER,
    FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE
  )`;

module.exports = {
  CREATE_FILES_TABLE_QUERY,
  CREATE_TRANSLATIONS_TABLE_QUERY
}